// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	models "UrlShorter/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UrlGetter is an autogenerated mock type for the UrlGetter type
type UrlGetter struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: _a0
func (_m *UrlGetter) GetUrl(_a0 models.Url) (models.Url, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUrl")
	}

	var r0 models.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Url) (models.Url, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(models.Url) models.Url); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Url)
	}

	if rf, ok := ret.Get(1).(func(models.Url) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlGetter creates a new instance of UrlGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlGetter {
	mock := &UrlGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
